### ISSUE TITLE
itemlist subwindow interferes with list item command

### ISSUE THREAD

**Issue by angband-import** [angband/angband#3680]
**Reported by non on 31 Dec 2011 07:10 UTC**
I have an itemlist subwindow which is sized to only display one item. So if there is more than one, the second line will say "...and 1 others."

Despite the obvious grammatical problem, the real problem is that if I use ], the list-items command, it seems to (erroneously) limit itself to one-line of output, and displays the "and 1 others" line.

It *should* display all the items, giving me a -more- prompt if necessary.

**Comment by angband-import** [comment]
**Comment by takkaria on 27 Apr 2013 23:16 UTC**
Assigning open bugs to 3.5 for fixing.

**Comment by angband-import** [comment]
**Modified by takkaria on 16 Oct 2013 09:13 UTC**

**Comment by angband-import** [comment]
**Comment by takkaria on 16 Oct 2013 09:18 UTC**
Point 1 fixed in b020e2c, pull request https://github.com/angband/angband/pull/276

**Comment by angband-import** [comment]
**Modified by bensemmler on 13 Nov 2013 04:33 UTC**

**Comment by angband-import** [comment]
**Comment by takkaria on 25 Nov 2013 22:37 UTC**
FIxed in https://github.com/angband/angband/pull/289

**Comment by angband-import** [comment]
**Comment by draconisPW on 26 Nov 2013 15:53 UTC**
As of dev-668-g13dc1db, when you reduce the horizontal size of the subwindow to minimal, the game crashes. Also the subwindow is not refreshed when you change levels until you move (monster list).

Edit: the game also crashes when resizing the object list subwindow vertically with 3 objects on the screen.

**Comment by angband-import** [comment]
**Comment by draconisPW on 27 Nov 2013 10:18 UTC**
Problem with subwindow not refreshed reported as #1808.

**Comment by angband-import** [comment]
**Comment by bensemmler on 1 Dec 2013 01:35 UTC**
Regarding these crashes, it would be helpful if crash logs/backtraces could be attached. I've added some safety checks, but in some cases, the crashes I'm getting are ending up in the OS X port code and not the actual object list code.

**Comment by angband-import** [comment]
**Comment by takkaria on 1 Dec 2013 21:56 UTC**
Potentially fixed in https://github.com/angband/angband/pull/302

**Comment by angband-import** [comment]
**Comment by draconisPW on 3 Dec 2013 14:59 UTC**
One last problem with the object list: when you look at the monster list and see the same monster at two different locations, the location is omitted; when you look at the object list and see the same object at two different locations, the location is not omitted and the closest is displayed. Feels weird.

**Comment by angband-import** [comment]
**Comment by draconisPW on 3 Dec 2013 15:26 UTC**
Replying to [comment:9 takkaria]:
> Potentially fixed in https://github.com/angband/angband/pull/302

Not fixed. Since I'm under Windows, I can't get any extra log/info about the crash, but it should be easy to track down since it always happens when you resize the subwindow horizontally until you have only 2 columns left.

**Comment by angband-import** [comment]
**Modified by takkaria on 7 Dec 2013 17:06 UTC**

**Comment by angband-import** [comment]
**Comment by draconisPW on 19 Dec 2013 16:03 UTC**
While we're at it, there's also a small glitch with the new object list: when using fuzzy detection, all body armor are displayed with a tabulation. For example:

```
You can see 3 objects:
*  an unknown item        <-- "a something" or "x somethings"
*     an unknown item     <-- body armor ("Bar Chain Mail", ...)
*  an unknown item        <-- "a something" or "x somethings"
```

The check for singular prefix should only be applied for items not marked as "aware".

```
if object_marked_aware(...) has_singular_prefix = TRUE;
```

**Comment by angband-import** [comment]
**Comment by draconisPW on 19 Dec 2013 16:44 UTC**
One more glitch: artifact body armor are displayed with a tabulation. For example:

```
You can see 4 objects:
(   a Cloak
( the Cloak Thorongil...
[     Chain Mail
[     the Chain Mail of Arvedui...
```

The check for singular prefix should only be applied for non-known artifacts.

```
if ((object_name_is_visible(...) || object_is_known(...)) && obj->artifact) has_singular_prefix = TRUE;
```

**Comment by angband-import** [comment]
**Comment by takkaria on 21 Dec 2013 14:33 UTC**
OK, so I've fixed those bugs but I can't reproduce the two-wide crash on OS X, Valgrind doesn't show up any problems on OS X either.  I think this is minor enough to not classify as a blocker.

**Comment by angband-import** [comment]
**Comment by draconisPW on 23 Dec 2013 15:23 UTC**
Fix applied in f05ea99a doesn't take into account soft armor.

**Comment by angband-import** [comment]
**Comment by bensemmler on 19 Mar 2016 02:38 UTC**
5d758d5 fixes most of the indentation issues with unidentified, pseudo'd, and identified armors. Indentation issues with fuzzy detection haven't been seen yet.

For the sake of tracking, I've checked the original issues and as many of the comments as possible. I propose closing this and opening new tickets as necessary.

**Comment by NickMcConnell** [comment]
Should have been closed before.
